pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'  # Opcional: Defina o namespace do aplicativo

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('produtor/', views.produtor, name='produtor'),
    path('vendedor/', views.vendedor, name='vendedor'),
    path('reset/', views.resetPedidos, name='reset_pedidos'),
    # Adicione outras URLs do aplicativo aqui
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
# Adicione outras URLs do projeto aqui
]

my_user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    TIPOS_USUARIO = [
        ('vendedor', 'Vendedor'),
        ('produtor', 'Produtor'),
    ]
    type = models.CharField(max_length=20, choices=TIPOS_USUARIO)
    confiavel = models.IntegerField()

pedidos/models.py
from django.db import models
from my_user.models import User



class Pedido(models.Model):
    id = models.PositiveIntegerField(unique=True, primary_key=True)
    cliente = models.CharField(max_length=255)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.SET_NULL)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return f'{self.id} - {self.cliente}'

pedidos/forms.py
from django import forms
from .models import Pedido

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['id', 'cliente']

my_user/views.py
from django.shortcuts import render

# Create your views here.

pedidos/views.py
from django.shortcuts import render, redirect
from .models import Pedido
from .forms import PedidoForm
from my_user.models import User
from django.views.decorators.csrf import csrf_protect

    
@csrf_protect
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        role = request.POST['role']
        
        # Verifique o valor de 'role' para determinar a cor do fundo e o título
        if role == 'produtor':
            background_color = '#ff0000'  # Cor do fundo para o produtor
            title = 'Entrando como produtor'
        elif role == 'vendedor':
            background_color = '#00ff00'  # Cor do fundo para o vendedor
            title = 'Entrando como vendedor'
        
        # Redirecione para a seção especificada (produtor ou vendedor)
        if role == 'produtor':
            return redirect('produtor')
        elif role == 'vendedor':
            return redirect('vendedor')

    return render(request, 'login.html')

def produtor(request):

    if request.method == 'POST':
        form = PedidoForm(request.POST)
        
        user = User.objects.filter(username='produção')[0]

        if form.is_valid():
            pedido = form.save(commit=False)
            pedido.created_by = user
            pedido.updated_by = user
            pedido.save()
            return redirect('produtor')

    else:
        form = PedidoForm()

    pedidos = Pedido.objects.all().order_by('-updated_at')
    return render(request, 'produtor.html', {'pedidos': pedidos, 'form': form})

def vendedor(request):
    pedidos = Pedido.objects.all().order_by('-updated_at')
    return render(request, 'vendedor.html', {'pedidos': pedidos})

def resetPedidos(request):
    pedidos, form = getPedidoForm()
    Pedido.objects.all().delete()
    return redirect('pedidos:home')

def getPedidoForm():
    pedidos = Pedido.objects.all().order_by('-updated_at')
    form = PedidoForm()
    return {pedidos, form}

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Formulário de Login</title>
    <style>
        body {
            background-color: #f2f2f2;
            transition: background-color 0.3s ease;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        .form-group input[type="text"],
        .form-group input[type="password"] {
            padding: 8px;
            width: 100%;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .form-group .btn {
            padding: 8px 12px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .form-group .btn.vendas {
            background-color: #4CAF50;
            color: white;
        }
        .submit {
            background-color: #412cb3;
            color: white;
        }

        .form-group .btn.producao {
            background-color: #ccc;
            color: black;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Formulário de Login</h1>
        <form action="" method="post">
          {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="senha" required>
            </div>
            <div class="form-group">
                <label>Selecione o Tipo:</label>
                <input type="button" class="btn producao" value="Produtor">
                <input type="button" class="btn vendas" value="Vendedor">
            </div>
            
            <div class="form-group">
                <input type="submit" class="submit" value="Login">
            </div>
        </form>
    </div>

    <script>
        const vendasButton = document.querySelector('.form-group input.vendas');
        const producaoButton = document.querySelector('.form-group input.producao');

        vendasButton.addEventListener('click', function() {
            document.body.style.backgroundColor = '#4CAF50';
        });
        producaoButton.addEventListener('click', function() {
            document.body.style.backgroundColor = '#ccc';
        });
    </script>
</body>
</html>

templates/produtor.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Pedidos</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }
      
      th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      form {
        margin-bottom: 20px;
      }
      
      input[type="text"] {
        padding: 6px;
        width: 200px;
      }
      
      input[type="submit"] {
        padding: 6px 12px;
        background-color: #4CAF50;
        color: white;
        border: none;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <h1>Registro de Pedidos Concluídos</h1>
    <h2>Bom dia meus produtores sz!</h2>

    <form id="pedidoForm" method="POST" action="{% url 'pedidos:produtor' %}">
      {% csrf_token %}
      <label for="cliente">Nome do Cliente:</label>
      <input type="text" id="cliente" name="cliente" required>
      
      <label for="id">Número do Pedido:</label>
      <input type="text" id="id" name="id" required>
      
      <input type="submit" value="Registrar Pedido">
    </form>

    <table id="pedidosTable">
      <thead>
        <tr>
          <th>Número do Pedido</th>
          <th>Nome do Cliente</th>
          <th>Data e Hora</th>
          <th>Registrado Por</th>
        </tr>
      </thead>
      
      <tbody>
        {% for pedido in pedidos %}
          <tr>
            <!-- <td>{{ pedido.id }}</td> -->
            <td>{{ pedido.id }}</td>
            <td>{{ pedido.cliente }}</td>
            <td>{{ pedido.updated_at }}</td>
            <td>{{ pedido.updated_by }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

templates/vendedor.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Pedidos</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }
      
      th, td {
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      form {
        margin-bottom: 20px;
      }
      
      input[type="text"] {
        padding: 6px;
        width: 200px;
      }
      
      input[type="submit"] {
        padding: 6px 12px;
        background-color: #4CAF50;
        color: white;
        border: none;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <h1>Registro de Pedidos Concluídos</h1>
    <h2>Bom dia a vocês vendedores <3</h2>

    <table id="pedidosTable">
      <thead>
        <tr>
          <th>Número do Pedido</th>
          <th>Nome do Cliente</th>
          <th>Data e Hora</th>
          <th>Registrado Por</th>
        </tr>
      </thead>
      
      <tbody>
        {% for pedido in pedidos %}
          <tr>
            <td>{{ pedido.id }}</td>
            <td>{{ pedido.cliente }}</td>
            <td>{{ pedido.updated_at }}</td>
            <td>{{ pedido.updated_by }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>